### ISSUE TITLE
Table 'xxx.users' doesn't exist

### ISSUE THREAD

**Issue by makeco** [thinkjs/think-cli#6]
假如数据库里有个USERS表（虽然不推荐大写），使用`thinkjs model users`创建了一个users.js文件，然后在控制器编写如下代码，会出现`ER_NO_SUCH_TABLE: Table 'xxx.users' doesn't exist`异常。
```js
const usersModel = this.model('users')
let data = await usersModel.select(); 
```
解决方法，在users.js文件中加上tableName的getter方法，返回大写的表名，查询就没问题了。
```js
module.exports = class extents this.Model {
    get tableName() {
        return 'USERS'
    }
}
```

**Comment by welefen** [comment]
恩，users 是模型名，跟表名不一致时需要手动配置表名
