### ISSUE TITLE
thinkjs  controller test报错

### ISSUE THREAD

**Issue by junhaotong** [thinkjs/think-cli#9]
![image](https://user-images.githubusercontent.com/20011131/29656633-983815d4-88e7-11e7-9372-a8cb19e082ed.png)

**Comment by junhaotong** [comment]
已经解决了,降低think-cli的版本

**Comment by makeco** [comment]
@junhaotong 经过自测，在ubuntu 16.04、window 7、mac均可正常生成控制器，如果没能解决你的问题，你可以找到报错路径的文件，使用`chown user.user index_gen.js` 修改文件属主（"user"为当前用户，执行一次即可），这样每次生成的控制器文件属主为“user”用户。

ubuntu 16.04
![image](https://user-images.githubusercontent.com/16967069/29703138-d9700cc2-89a6-11e7-801a-e915ff7a4451.png)

windows 7
![image](https://user-images.githubusercontent.com/16967069/29703315-99982e76-89a7-11e7-89fe-207917de8b98.png)
